version: "3.8"

services:
  web-scraping-backed:
    container_name: "web-scraping-backend"
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 1722:1722
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    command: yarn run dev
